### PR TITLE
pass bg_file to meta_background_set_file - closes #144

### LINKED ISSUE #144: FTBFS with mutter 3.15.4
Hi,

with mutter 3.15.4 budgie wm fails to build from source:

```
  CC       ui/budgie_wm-background.o
ui/background.c: In function ‘_update’:
ui/background.c:256:17: error: incompatible type for argument 2 of ‘meta_background_set_file’
                 meta_background_set_file(background, style);
                 ^
In file included from /usr/include/mutter/meta/meta-background-actor.h:26:0,
                 from ui/background.c:14:
/usr/include/mutter/meta/meta-background.h:70:6: note: expected ‘struct GFile *’ but argument is of type ‘GDesktopBackgroundStyle’
 void meta_background_set_file     (MetaBackground            *self,
      ^
ui/background.c:256:17: error: too few arguments to function ‘meta_background_set_file’
                 meta_background_set_file(background, style);
                 ^
In file included from /usr/include/mutter/meta/meta-background-actor.h:26:0,
                 from ui/background.c:14:
/usr/include/mutter/meta/meta-background.h:70:6: note: declared here
 void meta_background_set_file     (MetaBackground            *self,
      ^
make[2]: *** [ui/budgie_wm-background.o] Error 1
Makefile:603: recipe for target 'ui/budgie_wm-background.o' failed
```

### PR DESCRIPTION
**Pull request by LeoIannacone**
Fix fails to build with mutter > 3.14

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Wow I fail. cheers.
